### PR TITLE
Partially fix #11. The tol parameter default in get_roots_rect was in…

### LINKED ISSUE #11: get_roots_rect returns multiple (and sometimes inaccurate) variations of the same root.
The issue can be demonstrated using the additional test cases added to the fork here:
https://github.com/petersbingham/potapov_interpolation/blob/Potapov_PolyRootTests/Potapov_Code/tests/tests_Roots.py 

eg:

`test_Poly_Roots(11, printRoots=True, printPolys=False, printParams=False, doubleOnWarning=False)`

When running this example some stats are printed and then a list of roots (in the left column) obtained using numpy.roots and then another list obtained using get_roots_rect. The numbers in the right column (beside the roots) are the results of plugging the root back into the function (so obviously expect to be close to zero).

This is a 10th order polynomial, so expect 10 roots. The numpy in the test code does return the correct number of roots but get_roots_rect returns 22. The roots returned with get_roots_rect all appear clustered around the numpy root values. 

I've had a brief look at this and it appears to arise from applying muller to the outliers. This may therefore apply more accurately to the muller function or may be a numerical limitation of the routine,

### PR DESCRIPTION
**Pull request by petersbingham**
…correctly being overridden by the verbose parameter. When verbose was true the tol was equal to one and since this was less than the purge parameter several roots were both detected and returned. When verbose was false the tol was equal to zero and the muller appears to return the converged value after N under these circumstances. This commit includes polynomial tests for the get_roots_rect function.

### CODE REVIEW

**Comment by petersbingham** [comment]
I changed get_roots_rect to also return a code. I updated the client for this but please double check I haven't broken anything here.

**Comment by petersbingham** [comment]
Also, can you please let me know what your style rules are. I'm breaking these I think. I think I'm over your max line length. If you can let me know, I will fix to follow and squash into the PR.

**Comment by petersbingham** [comment]
The actual (partial) fix for the bug can be found on lines 393 and 430 (if you want to see the issue remove these fixes and run test_Roots_3()). I say partial since for high orders (using my poly test code) I'm still seeing some repeated roots so there must be something else going on here as well (I suspect non-convergence of the muller and have another fix for this, which, if valid, will be in my next PR). For the lower orders (eg N=11) all the repeated roots have been removed with this fix in place.

**Comment by vsoch** [comment]
@tabakg you should write some tests to cover your code so changes can be easily assessed for breaking anything.

**Comment by petersbingham** [comment]
Can be found at: https://github.com/petersbingham/pydelves/issues (NB: WIP)

**Review by tabakg — APPROVED** [review]

**Pull request merged**
